---
title: "DSA2101_Proj"
author: "Emily"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, message = FALSE, warning = FALSE, 
                      fig.align = "center",  out.width = "80%")
library(tidyverse)
library(readxl)
library(stringr)
library(lubridate)

```

## reading in data

```{r}
tuesdata <- tidytuesdayR::tt_load('2021-09-14')
billboard <- tuesdata$billboard
audio_features <- tuesdata$audio_features
```

# Clean Audio Features

```{r}
audio_clean <- audio_features %>%
  mutate(song_id = str_to_lower(song_id))
```

# Clean Billboard and join data
```{r}
#helper functions
remove_casing <- function(x){return(substr(x, 2, nchar(x)-1))}

clean_performer <- function(x){
  is_performer_dirty <- function(y){return(str_detect(y, "\\($"))}
  if (is.na(x)){
    return(x)
  }else if(is_performer_dirty(x)){
    return(substr(x, 1, nchar(x)-1))
  }else{
    return(x)
  }}
clean_featured <- function(x){
  is_featured_dirty <- function(y){return(str_detect(y, "\\)$"))}
  if (is.na(x)){
    return(x)
  }else if(is_featured_dirty(x)){
    return(substr(x, 1, nchar(x)-1))
  }else{
    return(x)
  }}
merge_big_genres <- function(x){
  if(is.na(x)){
    return(x)
  }
  if(str_detect(x, "pop") == TRUE){
    return("'pop'")
  }
  else if(str_detect(x, "rap") == TRUE){
    return("'rap'")
  }
  else if(str_detect(x, "rock") == TRUE){
    return("'rock'")
  }
  else if(str_detect(x, "jazz") == TRUE){
    return("'jazz'")
  }
  else if(str_detect(x, "metal") == TRUE){
    return("'metal'")
  }
  else if(str_detect(x, "disco") == TRUE){
    return("'disco'")
  }
  else if(str_detect(x, "hip hop") == TRUE){
    return("'hip hop'")
  }
  else if(str_detect(x, "contemporary") == TRUE){
    return("'contemporary'")
  }
  else if(str_detect(x, "blues") == TRUE){
    return("'blues'")
  }
  else if(str_detect(x, "soul") == TRUE){
    return("'soul'")
  }
  return(x)
}
transform_fusion <- function(x){
  count = 0 
  if(is.na(x)){
    return(x)
  }
  if (str_detect(x, "fusion") == TRUE){
    return ("'fusion'")
  }
  types = c("pop | pop", "rap | rap", "rock | rock", "jazz | jazz", "metal | metal", "disco | disco", "edm | edm", "soul | soul")
  for(i in types){
    if(str_detect(x, i)==TRUE){
      count = count + 1
      if (count == 2){
        return("'fusion'")
      }
    }
  }
  return(x)
}
# normalise duration
normalise_ms <- function(vector) {
  min_m = min(vector, na.rm = TRUE)
  max_m = max(vector, na.rm = TRUE)
  vector_norm = ifelse(!is.na(vector), (vector-min_m)/(max_m-min_m), NA)
  return(vector_norm)
}

# clean data
merged <- billboard %>%
  mutate(song_id = str_to_lower(song_id)) %>%
  left_join(audio_clean, by = "song_id", suffix = c("_billboard", "_audio")) %>%
  select(-c(url,performer_audio, spotify_track_id, song_audio, spotify_track_preview_url)) %>%
  mutate_at(vars(performer_billboard), str_to_lower) %>%
  
  # split the genres
  mutate_at(vars(spotify_genre), remove_casing) %>%         
  mutate(spotify_genre = strsplit(as.character(spotify_genre), ",")) %>%  
  unnest(spotify_genre) %>%                                               
  mutate_at(vars(spotify_genre), str_trim) %>%
  
  # separate main performer from featured performers
  separate(performer_billboard, into = c("performer", "featured"), sep = "featuring|starring") %>%
  mutate_at(vars(performer,featured), str_trim) %>%
  
  # trim away the brackets
  mutate(performer = str_trim(as.character(lapply(performer, clean_performer))),
         featured = str_trim(as.character(lapply(featured, clean_featured))) ) %>%
  
  # add features: all_time_peak and duration_mins (normalised)
  group_by(song_id) %>%
  mutate(all_time_peak = min(peak_position, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate_at(vars(week_id), mdy) %>%
  mutate(year = year(week_id),
         duration_mins = normalise_ms(spotify_track_duration_ms))

# df with cleaned genres
df_genres <- merged %>%
  mutate(spotify_genre = lapply(spotify_genre, transform_fusion)) %>%
  mutate(spotify_genre = lapply(spotify_genre, merge_big_genres)) %>%
  mutate_at(vars(spotify_genre), as.character)
```

# Emily Plots
## Butterfly plot FUNCTION 

```{r}
# takes in data with the newly merged variables and creates summary
create_sum <- function(data) {
  new <- data %>%
    select(-c(spotify_genre)) %>%
    distinct() %>%
    summarise(danceability = mean(danceability, na.rm = TRUE),
            energy = mean(energy, na.rm = TRUE),
            speechiness = mean(speechiness, na.rm = TRUE),
            acousticness = mean(acousticness, na.rm = TRUE),
            instrumentalness = mean(instrumentalness, na.rm = TRUE),
            liveness = mean(liveness, na.rm = TRUE),
            valence = mean(valence, na.rm = TRUE),
            explicit = sum(spotify_track_explicit, na.rm = TRUE)/n(),
            loudness = mean(ifelse(!is.na(loudness), 10^(loudness/10), NA), na.rm = TRUE),
            mode = mean(mode, na.rm = TRUE),
            duration = mean(duration_mins, na.rm = TRUE)
    )
  return(new)
}

## takes in TWO summarised data and their names. Transposes data then row binds
create_butterfly_data <- function(right, left, right_name, left_name) {
  right_t <- right %>%
    gather(key="features", value="value" ) %>%
    mutate(type = right_name) %>%
    arrange(desc(value))
  
  left_t <- left %>%
    gather(key="features", value="value" ) %>%
    mutate(type = left_name,
           value = - 1*value) %>%
    arrange(desc(value))

  butterfly_data <- rbind(right_t, left_t)
  
  return(butterfly_data)
}
```

## Butterfly Plot for before and after 1991

```{r}
before_1970 <- merged %>%
  filter(year <= 1991)
  
after_1970 <- merged %>%
  filter(year > 1991)
```

## ggplot     

```{r}
butterfly_data3 <- create_butterfly_data(create_sum(after_1970), create_sum(before_1970), "after_1991", "before_1991")

features_by_desc_values <- butterfly_data3 %>% filter(type == "after_1991") %>%
  arrange(value) %>% pull(features)
ggplot(butterfly_data3) + 
    geom_bar(aes(x = factor(features, level = features_by_desc_values) , y = value, fill = type), stat = 'identity') +
  scale_fill_manual(values = c("after_1991" = "#ccf2f3", "before_1991" = "#f7e9cc")) + 
    geom_text(data = subset(butterfly_data3, type == "after_1991") , aes(x = features, y = value, label = round(abs(value),2)), size = 3, vjust = .5, hjust = -0.3) +
    geom_text(data = subset(butterfly_data3, type == "before_1991") , aes(x = features, y = value, label = round(abs(value),2)), size = 3, vjust = .5, hjust = 1.2) +
    coord_flip(ylim = c(-1,1)) +
    scale_y_continuous(breaks = seq(-1,1,0.2)) +
  theme_classic() +
  labs(y = "value", x = "song characteristics", title = "Comparing Song Characteristics from before and after 1991")
    
```

# Kahseng Plots
## Average absolute change of song rankings each month

```{r}
# simplify merged dataset to select only necessary distinct rows
unique_songs <- merged %>%
  filter(year %in% c(2011:2020)) %>%  # can change this filter 
  select(c(year, week_id, song_id, week_position, peak_position)) %>%
  mutate(month = month(week_id, label = TRUE, abbr = TRUE), week = day(week_id)) %>%
  distinct() 
```

```{r}
ranking_change <- unique_songs %>%
  group_by(month) %>%
  group_by(song_id) %>%
  # for visual purposes
  arrange(week_id) %>%
  arrange(month, song_id) %>%
  # lag the week_position
  mutate(prev_week_pos = lag(week_position)) %>%
  na.omit() %>% # effectively removes the first row of all unique song_ids per month
  ungroup(month, song_id) %>%
  mutate(diff = abs(prev_week_pos-week_position)) %>%
  group_by(month) %>%
  summarise(abs_change = mean(sum(diff)/length(unique(song_id)), na.rm = TRUE))
``` 

```{r}
drop_out <- unique_songs %>% # data frame that finds out the number of songs that stay in the top 100 billboards for less than 4 weeks
  group_by(month, song_id) %>%
  summarise(count = n()) %>%
  filter(count < 4) %>%
  group_by(month) %>%
  summarise(count_drop_out = n()) %>%
  full_join(ranking_change)
```

```{r}
unique_songs_df <- unique_songs %>%
  group_by(month) %>%
  summarise(count_total = n()) %>%
  full_join(drop_out) %>%
  mutate(proportion_drop_out = 100*count_drop_out/count_total)
```

```{r}
ggplot(unique_songs_df) +
  geom_point(aes(x = month, y = abs_change, size = proportion_drop_out, color = count_total)) +
  scale_color_continuous(trans = "reverse") +
  theme_minimal() +
  labs(y = "Average absolute change of song rankings", x = "Month", title = "Average absolute change of song rankings each Month", color = "Total number \nof unique songs", size = "Songs (%) that \ndid not stay in the billboard \nfor > 3 weeks") +
  theme(legend.position = "bottom") + 
  scale_color_gradient(low = "#80b1d3", high = "#3a4143") +
  scale_y_continuous(breaks= seq(15,30,by=2))
```

# Xinyi Plots
## "Tile of Plots"

```{r} 
billboard_energy = merged %>%
  mutate(week_id = as_date(week_id, format="%m/%d/%Y"), 
         month = month(week_id, label = TRUE, abbr = TRUE),
         day = day(week_id),
         year = year(week_id)) %>%
  select(year, month, song_billboard, energy) %>%
  distinct()
```

```{r}
billboard_valence = merged %>%
  mutate(week_id = as_date(week_id, format="%m/%d/%Y"), 
         month = month(week_id, label = TRUE, abbr = TRUE),
         day = day(week_id),
         year = year(week_id)) %>%
  select(year, month, song_billboard, valence) %>%
  distinct()
```

```{r}
energy_month = billboard_energy %>%
  filter(year %in% c(2010:2015)) %>%
  group_by(month,year) %>%
  summarise(mean_energy= mean(energy, na.rm=TRUE),.groups='drop') 
```  

```{r}
energy_valence = billboard_valence %>%
  filter(year %in% c(2010:2020)) %>%
  group_by(month,year) %>%
  summarise(mean_valence= mean(valence, na.rm=TRUE),.groups='drop') 
```  

```{r}
ggplot(energy_month, aes(x=month, y=mean_energy, color=month)) +
  geom_boxplot() + 
  geom_point(position=position_jitterdodge()) +
  #scale_y_continuous(breaks= seq(0.4,0.8,by=0.05)) +
  theme_minimal()
```

```{r}
ggplot(energy_valence, aes(x=month, y=mean_valence, fill=month)) +
  geom_boxplot() + 
 # geom_point(position=position_jitterdodge()) + 
  labs(x="", y="Mean Varience", title ="Mean of Varience in 2010 to 2020, by Month") +
  scale_y_continuous(breaks= seq(0.42,0.58,by=0.02)) +
  scale_fill_brewer(type="qual", palette = "Set3") +
  theme_minimal() +
  theme(legend.position = "none")
```

# Zhiyi Plots

## top 10 genres across the dataframe, and their spread over the years
```{r}
# extracting the top genres over the entire dataset
top_genres = df_genres %>%
  group_by(spotify_genre) %>%
  summarize(n_songs = n()) %>%
  mutate(rank = rank(desc(n_songs))) %>%
  filter(rank <=10) %>%
  pull(spotify_genre)

top_overyears = df_genres %>%
  # spread of top genres over the years
  filter(spotify_genre %in% top_genres) %>%
  group_by(year, spotify_genre) %>%
  summarize(n_songs = n()) %>%
  arrange(year, desc(n_songs)) %>%
  # creating density plot
  ggplot(aes(x = year, fill = spotify_genre)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ spotify_genre) +
  theme_classic()

top_overyears
```